---
title: "DP_Week4"
author: "Cátia Reis"
date: "06/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data practical 4

<!--For this week's data practical, we will load some data and wrangle it a bit. I encourage you to do the following tasks on a data set of your choice -- ideally something you can use for your own research or something that interests you! There are lots of data sets out there, e.g.:

<!-- * Load a data set of your choosing -- or use the `gapminder` data set from the dslabs R library as discussed in this report -->

```{r}
library(readr)
library(dplyr)
skate_sounds <- read.csv("https://raw.githubusercontent.com/the-pudding/data/master/skate-music/soundtrack_data.csv")
str(skate_sounds)
```
<!-- * Filter the data by two variables -- e.g., countries of your choice -- and save the results to a new data frame -->

I am filtering the data set to have an overview of electronic music used in skate videos. 

```{r}
library(dplyr)
skate_new<-skate_sounds %>% filter(genre=="Electronic") %>% select(artist,tote,genre)
```

In the following code, the first rows are displayed. 
```{r}
head(skate_new)
```


Now, we can find the last rows. 
```{r}
tail(skate_new)
```

Here, you can see the structure of the dataset. 
```{r}
str(skate_new)
```

```{r}
skate<-skate_new %>% arrange(tote,artist,genre)
skate
```


Let's filter the na's

```{r}
filtered_na<-skate_new %>% filter(!is.na(tote))

```


We are going to join the following two datasets.

```{r}

library(datasets)
library(dslabs)


```
```{r}

data(murders)
data(results_us_election_2016)
```




